# make/help.mk — the hand-crafted help target.
#
# Hand-written, never grep-generated: grouping, order and emphasis are the
# point (agentic-skeleton references/makefile-pattern.md). It lives in its own
# file because it is documentation of the whole interface, and the root
# Makefile should read as build logic.

.PHONY: help

## help: Display this help message with all available targets
help:
	@echo ""
	@echo "$(BOLD)$(CYAN)$(APP_NAME)$(RESET)"
	@echo "$(CYAN)════════════════════════════════════════════════════$(RESET)"
	@echo ""
	@echo "$(BOLD)Setup$(RESET)"
	@echo "  $(GREEN)make bootstrap$(RESET)            Versions.xcconfig + xcodegen + hooks + gems"
	@echo "  $(GREEN)make regenerate$(RESET)           Just versions + xcodegen (what every build runs)"
	@echo "  $(GREEN)make env$(RESET)                  Create .env from .env.example"
	@echo "  $(GREEN)make env-check$(RESET)            Verify .env is present"
	@echo ""
	@echo "$(BOLD)Build (macOS + Xcode 26 only)$(RESET)"
	@echo "  $(GREEN)make build$(RESET)                Build the iOS app (alias: build-ios)"
	@echo "  $(GREEN)make build-watch$(RESET)          Build the watchOS app"
	@echo "  $(GREEN)make build-mac$(RESET)            Build the macOS app"
	@echo "  $(GREEN)make build-all$(RESET)            Build every platform present in this repo"
	@echo "  $(GREEN)make test$(RESET)                 Unit tests on $(DEVICE)"
	@echo "  $(GREEN)make ui-test$(RESET)              UI/snapshot tests ($(SCHEME_UI) scheme)"
	@echo "  $(GREEN)make typecheck$(RESET)            build-for-testing, no run"
	@echo ""
	@echo "$(BOLD)Verify$(RESET)"
	@echo "  $(GREEN)make lint$(RESET)                 SwiftLint (when installed) + architecture gate"
	@echo "  $(GREEN)make audit$(RESET)                Privacy manifest, usage strings, SPM-only, secrets"
	@echo "  $(GREEN)make validate$(RESET)             lint + typecheck + architecture + version + skills"
	@echo "  $(GREEN)make verify$(RESET)               The full gate chain (macOS) — same as the completion gate"
	@echo "  $(GREEN)make ci-linux$(RESET)             Every gate that runs without Xcode (CI's gates job)"
	@echo "  $(GREEN)make check-docs$(RESET)           Required collaboration files (VIBE.yaml)"
	@echo "  $(GREEN)make check-links$(RESET)          Relative links between markdown files resolve"
	@echo "  $(GREEN)make check-precommit$(RESET)      pre-commit hook is actually installed"
	@echo "  $(GREEN)make check-skeleton$(RESET)       Drift vs the installed agentic-skeleton"
	@echo "  $(GREEN)make sync-skeleton$(RESET)        Pull skeleton-owned files forward"
	@echo "  $(GREEN)make check-skills$(RESET)         Advisory: applied-skill provenance"
	@echo "  $(GREEN)make stamp-skill$(RESET)          Record a skill: SKILL=<id> [VERSION=x.y.z]"
	@echo "  $(GREEN)make spinner-sync$(RESET)         Corpus .txt → .claude/settings.json"
	@echo "  $(GREEN)make spinner-check$(RESET)        Fail if settings.json is out of sync"
	@echo ""
	@echo "$(BOLD)Versioning (required before every commit)$(RESET)"
	@echo "  $(GREEN)make version$(RESET)              Print current VERSION"
	@echo "  $(GREEN)make bump-patch$(RESET)           x.y.Z+1 — fixes, docs, refactor"
	@echo "  $(GREEN)make bump-minor$(RESET)           x.Y+1.0 — additive, backward-compatible"
	@echo "  $(GREEN)make bump-major$(RESET)           X+1.0.0 — breaking change"
	@echo ""
	@echo "$(BOLD)Release (fastlane — see docs/release-automation.md)$(RESET)"
	@echo "  $(GREEN)make testflight$(RESET)           Archive + upload to TestFlight"
	@echo "  $(GREEN)make screenshots$(RESET)          Capture App Store screenshots"
	@echo "  $(GREEN)make metadata-push$(RESET)        Push metadata + screenshots to ASC"
	@echo "  $(GREEN)make release$(RESET)              precheck, then submit for review"
	@echo "  $(GREEN)make asc-status$(RESET)           Dump App Store Connect state"
	@echo "  $(GREEN)make asc-bootstrap$(RESET)        Register bundle IDs + capabilities"
	@echo "  $(GREEN)make notarize-mac$(RESET)         Developer ID build + notarytool"
	@echo "  $(YELLOW)mac_beta / certs have no Make target by contract —$(RESET)"
	@echo "  $(YELLOW)run them as: $(FASTLANE) mac_beta | certs$(RESET)"
	@echo ""
	@echo "$(BOLD)Maintenance$(RESET)"
	@echo "  $(GREEN)make clean$(RESET)                Remove build output + the generated project"
	@echo "  $(GREEN)make info$(RESET)                 Show project state"
	@echo ""
	@echo "$(BOLD)Completion$(RESET)"
	@echo "  $(GREEN)make check-if-the-agent-can-consider-this-task-completed$(RESET)"
	@echo "    Final verification gate (required before declaring a task complete)"
	@echo ""
	@echo "$(BOLD)Variables$(RESET)"
	@echo "  DEVICE=$(DEVICE)  ·  WATCH_DEVICE=$(WATCH_DEVICE)"
	@echo "  (override: make test DEVICE='iPhone 17 Pro')"
	@echo ""

