#!/usr/bin/env bash
#
# generate-build-info.sh — stamp MyApp/Generated/BuildInfo.swift.
#
# Wired as project.yml's `preGenCommand`, so a bare `xcodegen generate` (and
# therefore `make bootstrap` and every build target) refreshes it. Also safe to
# run by hand.
#
# The emitted type conforms to `BuildInfoProviding` (MyApp/Services/AppInfo.swift).
# The generated file is `optional: true` in project.yml and gitignored, so no
# always-compiled source may reference it; wiring is one line the app owner adds:
#
#     AppInfo.current = GeneratedBuildInfo()      // in MyAppApp.init()
#
# Idempotent by content: the file is written only when it would change, so
# Xcode's incremental build does not recompile the module on every run. That is
# also why NOTHING here carries a wall-clock build timestamp — a timestamp makes
# the content differ on every invocation and quietly defeats the whole point.
#
# Inputs (all optional; every one has a git/VERSION-derived fallback):
#   $SRCROOT                  repo root (Xcode passes it)
#   $MARKETING_VERSION        else `cat VERSION` (ADR-0007)
#   $CURRENT_PROJECT_VERSION  else `git rev-list --count HEAD`
#   $BUILDINFO_APP_DIR        else MyApp

set -euo pipefail

SRC="${SRCROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
cd "$SRC"

APP_DIR="${BUILDINFO_APP_DIR:-MyApp}"
OUT_DIR="$APP_DIR/Generated"
OUT_FILE="$OUT_DIR/BuildInfo.swift"

# --- Version (same two sources as Config/Versions.xcconfig) -----------------

marketing="${MARKETING_VERSION:-}"
if [ -z "$marketing" ] && [ -f VERSION ]; then
    marketing="$(tr -d ' \t\r\n' < VERSION)"
fi
[ -n "$marketing" ] || marketing="0.0.0"

build="${CURRENT_PROJECT_VERSION:-}"
if [ -z "$build" ]; then
    build="$(git rev-list --count HEAD 2>/dev/null || echo 1)"
fi
[ "$build" != "0" ] || build=1

# --- Git provenance (degrade gracefully outside a checkout) -----------------

if git rev-parse --git-dir >/dev/null 2>&1; then
    sha_short="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
    sha_full="$(git rev-parse HEAD 2>/dev/null || echo unknown)"
    commit_date="$(git log -1 --format=%cs 2>/dev/null || echo unknown)"
    if git diff-index --quiet HEAD -- 2>/dev/null; then
        is_dirty="false"
        dirty_suffix=""
    else
        is_dirty="true"
        dirty_suffix="+dirty"
    fi
else
    sha_short="unknown"; sha_full="unknown"; commit_date="unknown"
    is_dirty="false"; dirty_suffix=""
fi

# --- Render -----------------------------------------------------------------

# A heredoc NESTED INSIDE $( ) breaks macOS /bin/bash 3.2 — its substitution
# parser quote-scans the heredoc body, so an apostrophe or backtick in a
# comment reads as an unclosed string. Render to a temp file; cmp keeps the
# content-hash idempotency (no rewrite → no Xcode recompile cascade).
mkdir -p "$OUT_DIR"
tmp="$(mktemp "${TMPDIR:-/tmp}/BuildInfo.swift.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
cat > "$tmp" <<EOF
// swiftlint:disable all
// AUTO-GENERATED by scripts/apple/generate-build-info.sh — DO NOT EDIT.
// Gitignored and \`optional: true\` in project.yml: absent on a fresh clone.

import Foundation

/// Build metadata captured from VERSION + git at generate time.
///
/// Conforms to \`BuildInfoProviding\`, so the Settings screen shows git
/// provenance the moment the app assigns it:
/// \`AppInfo.current = GeneratedBuildInfo()\`.
@MainActor
struct GeneratedBuildInfo: BuildInfoProviding {
    static let marketingVersion = "${marketing}"
    static let buildNumber = "${build}"
    static let commitShortSHA = "${sha_short}${dirty_suffix}"
    static let commitFullSHA = "${sha_full}"
    static let commitDate = "${commit_date}"
    static let isDirty = ${is_dirty}

    var versionLabel: String { Self.marketingVersion }
    var buildLabel: String { Self.buildNumber }
    var provenanceLabel: String? { "\\(Self.commitShortSHA) · \\(Self.commitDate)" }
}
EOF

if [ -f "$OUT_FILE" ] && cmp -s "$tmp" "$OUT_FILE"; then
    echo "BuildInfo.swift unchanged (skip write)"
    exit 0
fi

mv "$tmp" "$OUT_FILE"
echo "Wrote $OUT_FILE (v${marketing} build ${build} sha=${sha_short}${dirty_suffix})"
